//created on: Apr 2, 2019
package rule1pkg

//list any import classes here.



//declare any global variables here





rule "Rule 01"   
    when
        eval (1==1)
    then
        System.out.println("POC DROOLS: Rule 01 Works");
end

//rule "Your Second Rule"
    //include attributes such as "salience" here...
//    when
        //conditions
//    then
        //actions

//end
